# Generated by Django 4.0.2 on 2022-04-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jp_candles_app', '0003_alter_product_options_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_sale', models.DateField()),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='jp_candles_app.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='jp_candles_app.sale')),
            ],
        ),
    ]
